# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 09:57
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import myApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='标题')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.Category')),
            ],
            options={
                'verbose_name': '小说分类',
                'db_table': 't_category',
                'verbose_name_plural': '小说分类',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='内容')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '小说章节',
                'db_table': 't_chapter',
                'ordering': ['publish_time'],
            },
        ),
        migrations.CreateModel(
            name='Novels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_title', models.CharField(max_length=50, unique=True, verbose_name='小说名字')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('intro', models.CharField(max_length=255, verbose_name='小说简介')),
                ('content', models.TextField(verbose_name='详细说明')),
                ('icon', models.ImageField(upload_to=myApp.models.save_files_path, verbose_name='小说封面')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Category', verbose_name='分类名')),
            ],
            options={
                'verbose_name': '文章',
                'db_table': 't_novel',
                'verbose_name_plural': '文章',
                'ordering': ['publish_time'],
            },
        ),
        migrations.CreateModel(
            name='RollSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('free_level', models.IntegerField(choices=[(0, '免费'), (1, 'VIP')], default=0, verbose_name='免费等级')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Novels', verbose_name='所属文章')),
            ],
            options={
                'verbose_name': '卷级',
                'db_table': 't_roll',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标题')),
                ('describe', models.CharField(max_length=200, verbose_name='描述')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '标签',
                'db_table': 't_tag',
                'verbose_name_plural': '标签',
                'ordering': ['-add_time'],
            },
        ),
        migrations.AddField(
            model_name='novels',
            name='tags',
            field=models.ManyToManyField(to='myApp.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.RollSet', verbose_name='所属章节'),
        ),
    ]
