# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='describe',
            field=models.CharField(blank=True, max_length=200, verbose_name='描述'),
        ),
    ]
