# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='账号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('nickName', models.CharField(max_length=50, verbose_name='用户名')),
                ('icon', models.ImageField(default='', upload_to='icon/images', verbose_name='用户头像')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='手机号码')),
                ('email', models.CharField(default='', max_length=16, verbose_name='邮箱')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('source', models.CharField(default='', max_length=50, verbose_name='来源')),
            ],
            options={
                'verbose_name': '用户',
                'db_table': 't_user',
                'verbose_name_plural': '用户',
            },
        ),
    ]
